"""Versioned little-endian packed weight file; decode uses only saved bytes.

Low-bit indices are bit-packed LSB first, each row has an IEEE binary16 scale.
Excluded parameters are binary16; buffers retain their original dtype. Rotations
are regenerated by NumPy QR from stored seeds (runtime must be pinned). Exact
float64 codebooks are embedded. File size includes JSON metadata and all buffers.
This is a storage codec, not an integer inference backend.
"""
import json
import struct
from functools import lru_cache
from pathlib import Path
import numpy as np
import torch
from quantizers import random_orthogonal
from corrected_eval import make_tensor_seed, parse_method

@lru_cache(maxsize=128)
def rotation(n,seed):
    return random_orthogonal(n,seed)

def pack_codes(x,bits):
    x=np.asarray(x,dtype=np.uint8).reshape(-1)
    if bits not in (2,3,4,8) or np.any(x.astype(np.uint16)>=2**bits):
        raise ValueError('invalid code width or value')
    b=(x[:,None]>>np.arange(bits,dtype=np.uint8))&1
    return np.packbits(b.reshape(-1),bitorder='little').tobytes()

def unpack_codes(raw,bits,count):
    if len(raw)!=(count*bits+7)//8:
        raise ValueError('invalid packed length')
    b=np.unpackbits(np.frombuffer(raw,dtype=np.uint8),bitorder='little')[:count*bits]
    return (b.reshape(-1,bits)*(1<<np.arange(bits))).sum(1).astype(np.uint8)

def save_model(path,model,names,method,bits,codebooks,protected):
    params=set(dict(model.named_parameters()))
    records=[]; blobs=[]; offset=0
    def add(raw):
        nonlocal offset
        location=[offset,len(raw)]; blobs.append(raw); offset+=len(raw)
        return location
    for key,tensor in model.state_dict().items():
        a=tensor.detach().cpu().numpy()
        record={'name':key,'shape':list(a.shape),'original_dtype':a.dtype.str}
        if key not in names or method in ('fp32','fp16'):
            target='<f2' if key in params and method!='fp32' else a.dtype.str
            value=a.astype(target)
            if not np.isfinite(value).all(): raise ValueError(f'overflow: {key}')
            record.update(kind='raw',dtype=value.dtype.str,data=add(value.tobytes()))
        else:
            b=8 if key in protected or method=='int8_minmax' else bits
            rotated,grid=(False,'int8') if b==8 else parse_method(method)
            rows=a.astype(np.float64).reshape(a.shape[0],-1)
            n=rows.shape[1]
            rotated=rotated and n>=64
            seed=make_tensor_seed(0,names.index(key))
            if grid=='normal_codebook':
                scales=np.maximum(np.linalg.norm(rows,axis=1),1e-12)/np.sqrt(n)
                y=rows/scales[:,None]
                if rotated: y=y@rotation(n,seed).T
                cb=codebooks[b]
                indices=np.searchsorted((cb[:-1]+cb[1:])/2,y).astype(np.uint8)
            else:
                y=rows@rotation(n,seed).T if rotated else rows
                scales=np.maximum(np.max(np.abs(y),axis=1),1e-12)/(127 if b==8 else 2**b-1)
                if b==8:
                    indices=(np.clip(np.round(y/scales[:,None]),-127,127)+127).astype(np.uint8)
                else:
                    mag=np.minimum(2*np.floor(np.abs(y)/(2*scales[:,None]))+1,2**b-1)
                    q=np.where(y<0,-mag,mag)
                    indices=((q+2**b-1)/2).astype(np.uint8)
            scale16=scales.astype('<f2')
            if not np.isfinite(scale16).all(): raise ValueError(f'scale overflow: {key}')
            record.update(kind='quantized',bits=b,grid=grid,rotated=rotated,seed=seed,
                          data=add(pack_codes(indices,b)),scales=add(scale16.tobytes()),
                          scale_underflows=int(np.sum((scale16==0)&(scales>0))))
        records.append(record)
    meta={'format':1,'scale_dtype':'<f2','numpy_version':np.__version__,
          'method':method,'bits':bits,'codebooks':{str(k):v.tolist() for k,v in codebooks.items()},
          'records':records,'payload_bytes':offset}
    header=json.dumps(meta,separators=(',',':')).encode()
    Path(path).write_bytes(b'DFQPACK1'+struct.pack('<Q',len(header))+header+b''.join(blobs))
    return meta

def load_model(path):
    raw=Path(path).read_bytes()
    if raw[:8]!=b'DFQPACK1': raise ValueError('invalid format')
    length=struct.unpack('<Q',raw[8:16])[0]
    meta=json.loads(raw[16:16+length]); payload=raw[16+length:]
    if len(payload)!=meta['payload_bytes']: raise ValueError('truncated payload')
    def read(loc):
        start,size=loc
        return payload[start:start+size]
    state={}
    for r in meta['records']:
        shape=r['shape']
        if r['kind']=='raw':
            a=np.frombuffer(read(r['data']),dtype=r['dtype']).reshape(shape).astype(r['original_dtype'])
        else:
            indices=unpack_codes(read(r['data']),r['bits'],int(np.prod(shape))).reshape(shape[0],-1)
            scales=np.frombuffer(read(r['scales']),dtype='<f2').astype(np.float64)
            if r['grid']=='normal_codebook':
                y=np.asarray(meta['codebooks'][str(r['bits'])])[indices]
            elif r['grid']=='int8': y=indices.astype(np.float64)-127
            else: y=2*indices.astype(np.float64)-(2**r['bits']-1)
            if r['rotated']: y=y@rotation(y.shape[1],r['seed'])
            a=(y*scales[:,None]).reshape(shape).astype(r['original_dtype'])
        state[r['name']]=torch.from_numpy(a.copy())
    return state,meta

def replace_raw_parameters(path,replacements):
    """Replace saved bias bytes without requantizing any weight codes or scales."""
    raw=bytearray(Path(path).read_bytes())
    length=struct.unpack('<Q',raw[8:16])[0]
    meta=json.loads(raw[16:16+length]); start=16+length
    for key,value in replacements.items():
        record=next(r for r in meta['records'] if r['name']==key)
        if record['kind']!='raw': raise ValueError('requires raw parameter')
        a=value.detach().cpu().numpy().astype(record['dtype'])
        if not np.isfinite(a).all(): raise ValueError('nonfinite bias')
        offset,size=record['data']; encoded=a.tobytes()
        if len(encoded)!=size: raise ValueError('wrong shape')
        raw[start+offset:start+offset+size]=encoded
    Path(path).write_bytes(raw)
